apiVersion: v1
kind: Service
metadata:
  name: anzbank-test-app-loadbalancer-service
  namespace: technical-test
  labels:
    app: anzbank-test-app
spec:
  type: LoadBalancer
  selector:
    app: anzbank-test-app
  ports:
    - port: 80
      targetPort: 8080