# Node docker image on which our code would run
image: node:14.18.1

# #This command is run before all the jobs
# before_script:
#   - npm install

stages:
  - test
  - buildimage
  - deploy

test:
  stage: test
  before_script:
    - npm install
    - chmod 0777 ./node_modules/.bin/mocha
  script:
    - npm run test

buildimage:
  stage: buildimage
  services:
    - docker:20.10.9-dind
  image: docker:20.10.9
  script:
    - bash build_and_push_docker_image.sh

deploy:
  stage: deploy
  services:
    - docker:20.10.9-dind
  image: docker:20.10.9
  before_script: 
    - pip install awscli
  script:
    - aws eks --region ap-southeast-2 update-kubeconfig --name $EKS_CLUSTER_NAME
    - bash deployments/deploy_to_eks.sh
  only: # deployment occurs for code push only to main branch
   - main