name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Login to Docker Hub'
      run: docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rajarshi-test-github-actions/nodejs
    - name: 'Push the Docker Image'
      run: docker push rajarshi-test-github-actions/nodejs
        env:
          CI: true
